extends TileMapLayer
## Procedural Map Generator
## Each TileSetAtlasSource ID listed in TILESET_SOURCE_IDS must have the
## following custom data layers set for each tile:
##	start_offset: how many tiles to offset this tile left/right before drawing it.
##	end_offset: how many tiles to offset the next tile left/right.
##	safe_zone: true if this tile can be used for the begining and ending sections
##		of the map, false otherwise.
##	probability: (standard, not custom property) how likly the tile is to be
## 		generated by the rng.
##
## TODO:
## Load map in chunks, rather than all at once
## Implement safe zones
## Special tiles?


const MAP_TILE_SOURCE_IDS: Array[int] = [2]
const BACKGROUND_TILE_SOURCE_IDS: Array[int] = [0]

var rng: RandomNumberGenerator = RandomNumberGenerator.new()
var map_tiles: TileList = TileList.new(tile_set)
var background_tiles: TileList = TileList.new(tile_set)

@export var map_seed: String = ""
@export var map_length: int = 0 # Set to 0 to generate based on map_seed

## List of Tiles.
## Allows randomly picking tiles
class TileList:
	var _tile_list: Array[Tile] = []
	var _tile_list_probabilities: PackedFloat32Array = []
	var _tile_set: TileSet
	var _rng: RandomNumberGenerator = RandomNumberGenerator.new()
	
	func _init(tile_set: TileSet) -> void:
		_tile_set = tile_set
		
	func set_rng(rng: RandomNumberGenerator) -> void:
		_rng = rng
	
	## Populates the TileList with all of the tiles from the given source.
	## Includes alternative tiles as well.
	## callback should be a function that creates a Tile, or a subclass of Tile,
	## and calls add_tile(). Not a great way of doing this, but here we are.
	func populate_from_source(source_id: int, callback: Callable) -> void:
		if not _tile_set.get_source(source_id) is TileSetAtlasSource:
			printerr("TileSet Source ID %s in TILESET_SOURCE_IDS is not of type TileSetAtlasSource." % [source_id])
			return
			
		var source: TileSetAtlasSource = _tile_set.get_source(source_id)
	
		for tile_index: int in source.get_tiles_count():
			var atlas_coords: Vector2i = source.get_tile_id(tile_index)
			callback.call(self, _tile_set, source_id, atlas_coords, 0)
			
			for alternative_index: int in source.get_alternative_tiles_count(atlas_coords):
				var alternative_tile: int = source.get_alternative_tile_id(atlas_coords, alternative_index)
				callback.call(self, _tile_set, source_id, atlas_coords, alternative_tile)
	
	func add_tile(tile: Tile) -> void:
		_tile_list.append(tile)
		_tile_list_probabilities.append(tile.get_probability())
		
	func pick_random() -> Tile:
		return _tile_list[_rng.randi_range(0, _tile_list.size())]
	
	func pick_random_weighted() -> Tile:
		return _tile_list[_rng.rand_weighted(_tile_list_probabilities)]
	

## Class for TileSetAtlasSource based tiles
class Tile:
	var _tileset: TileSet
	var _source_id: int
	var _atlas_coords: Vector2i
	var _alternative_tile: int
	
	func _init(tileset: TileSet, source_id: int, atlas_coords: Vector2i, alternative_tile: int) -> void:
		_tileset = tileset
		_source_id = source_id
		_atlas_coords = atlas_coords
		_alternative_tile = alternative_tile
		
	func _to_string() -> String:
		return "Source: %s, Tile: %s, Alternative: %s" % [_source_id, _atlas_coords, _alternative_tile]
	
	func get_tileset_source() -> TileSetAtlasSource:
		return _tileset.get_source(_source_id)
		
	func get_tile_data() -> TileData:
		return get_tileset_source().get_tile_data(_atlas_coords, _alternative_tile)
		
	func get_custom_property(name: String) -> Variant:
		if not get_tile_data().has_custom_data(name):
			printerr("Tile %s missing custom data property %s" % [self, name])
			return null
		
		return get_tile_data().get_custom_data(name)
		
	func get_tile_size() -> Vector2i:
		return get_tileset_source().get_tile_size_in_atlas(_atlas_coords)
		
	func get_probability() -> float:
		return get_tile_data().probability
		
	func get_place_position(coords: Vector2i) -> Vector2i:
		return coords
		
	func get_next_position(coords: Vector2i) -> Vector2i:
		return coords + Vector2i(0, get_tile_size().y)
		
	## Takes in the TileMapLayer and TileMap coords to begin placing the tile.
	func place_tile(tilemap: TileMapLayer, coords: Vector2i) -> void:
		tilemap.set_cell(
			get_place_position(coords),
			_source_id,
			_atlas_coords,
			_alternative_tile)


class MapTile extends Tile:
	func get_place_position(coords: Vector2i) -> Vector2i:
		@warning_ignore("unsafe_cast")
		return coords + Vector2i(get_custom_property("start_offset") as int, 0)
		
	func get_next_position(coords: Vector2i) -> Vector2i:
		@warning_ignore("unsafe_cast")
		return get_place_position(coords) + Vector2i(
			get_custom_property("end_offset") as int,
			get_tile_size().y)
		

class BackgroundTile extends Tile:
	## Returns the x offset from tile to place this background tile.
	## Note: does not include place_position offsets.
	func get_offset_from_tile(tile: Tile) -> int:
		return floor((tile.get_tile_size().x / 2.0) + (get_tile_size().x / 2.0))


func _update_map_seed() -> void:
	if map_seed:
		var hashed_seed: int = map_seed.hash()
		print("Using seed: %s (%d)" % [map_seed, hashed_seed])
		rng.seed = hashed_seed
	else:
		print("No seed provided, using random seed.")
		rng.randomize()
		
		
func _update_map_length() -> void:
	if map_length <= 0:
		# Generate based on map_seed
		var length: float = sqrt(map_seed.length()) * 30.0
		var max_length: int = ceil(length * 1.10)
		var min_length: int = floor(length * 0.90)
		
		map_length = rng.randi_range(min_length, max_length)
		print("Generated map length: %s" % [map_length])
	else:
		# Use specified map length
		print("Using provided map length: %s" % [map_length])


func _populate_tile_lists() -> void:
	# Auto populate standard tilesets
	var map_tile_lambda: Callable = func (
			tile_list: TileList,
			tile_set_: TileSet,
			source_id: int,
			atlas_coords: Vector2i,
			alternative_tile: int) -> void:
		tile_list.add_tile(MapTile.new(tile_set_, source_id, atlas_coords, alternative_tile))
		
	for source_id: int in MAP_TILE_SOURCE_IDS:
		map_tiles.populate_from_source(source_id, map_tile_lambda)
		
	var background_tile_lambda: Callable = func (
			tile_list: TileList,
			tile_set_: TileSet,
			source_id: int,
			atlas_coords: Vector2i,
			alternative_tile: int) -> void:
		tile_list.add_tile(BackgroundTile.new(tile_set_, source_id, atlas_coords, alternative_tile))
	
	for source_id: int in BACKGROUND_TILE_SOURCE_IDS:
		background_tiles.populate_from_source(source_id, background_tile_lambda)

	
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	map_tiles.set_rng(rng)
	background_tiles.set_rng(rng)
	
	_update_map_seed()
	_update_map_length()
	_populate_tile_lists()
	clear()
	
	var coords: Vector2i = Vector2i(0, 0)
	for y: int in map_length:
		var tile: MapTile = map_tiles.pick_random_weighted()
		print(tile)
		tile.place_tile(self, coords)
		
		# Background tiles
		var background_tile: BackgroundTile
		var pos: Vector2i
		for y_offset: int in tile.get_tile_size().y:
			# Left (negative)
			background_tile = background_tiles.pick_random_weighted() as BackgroundTile
			pos = tile.get_place_position(coords) + Vector2i(-background_tile.get_offset_from_tile(tile), y_offset)
			background_tile.place_tile(self, pos)
			
			# Right (positive)
			background_tile = background_tiles.pick_random_weighted() as BackgroundTile
			pos = tile.get_place_position(coords) + Vector2i(background_tile.get_offset_from_tile(tile), y_offset)
			background_tile.place_tile(self, pos)
		
		coords = tile.get_next_position(coords)


func _physics_process(_delta: float) -> void:
	pass
